[parity]
chain = "aura.json"
base_path = "node0"

[account]
unlock = ["0xfc04c8c22961aa43cffaba9880aa105c55ea7069"]
password = ["node.pwds"]

[network]
port = 30300
min_peers = 6
max_peers = 12
nat = "any"
id = 6652
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
max_pending_peers = 64
no_serve_light = false
reserved_peers="./reservedPeers.enode"
reserved_only=true

[rpc]
port = 8545
interface = "all"
cors=["*"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[websockets]
port = 8180
interface = "all"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[ipc]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub"]

[mining]
author = "0xfc04c8c22961aa43cffaba9880aa105c55ea7069"
engine_signer = "0xfc04c8c22961aa43cffaba9880aa105c55ea7069"
force_sealing = true
reseal_on_txs = "none"

