[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity2"
[network]
port = 30302
[rpc]
port = 8542
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
hosts = ["all"]
interface = "all"
[ui]
port = 8182
interface = "all"
[websockets]
port = 8452
interface = "all"
[ipc]
disable = true
[account]
password = ["node.pwds"]
#[mining]
#engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
#reseal_on_txs = "none"
