[parity]
chain = "aura.json"
base_path = "node3"

[account]
unlock = ["0x91f4385a5ba8f6976b0fd11d4619378d35e8196a"]
password = ["node.pwds"]

[network]
port = 30303
min_peers = 6
max_peers = 12
nat = "any"
id = 6652
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_peers="./reservedPeers.enode"
reserved_only=true

[rpc]
port = 8548
interface = "all"
cors=["*"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[websockets]
disable = false
port = 8178
interface = "127.0.0.1"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[ipc]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub"]

[mining]
author = "0x91f4385a5ba8f6976b0fd11d4619378d35e8196a"
engine_signer = "0x91f4385a5ba8f6976b0fd11d4619378d35e8196a"
notify_work = ["http://localhost:3004"]
gas_cap = "6283184"
tx_gas_limit = "6283184"
force_sealing = true
reseal_on_txs = "none"
