[parity]
chain = "demo.json"
base_path = "parity2"

[account]
unlock = ["0xda1e1cf8bbc40ffedf7c1a3f0952be541cc62f97"]
password = ["node.pwds"]

[network]
port = 30302
min_peers = 6
max_peers = 12
nat = "any"
id = 6652
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_peers="./reservedPeers.enode"
reserved_only=true

[rpc]
port = 8547
interface = "all"
cors=["*"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[websockets]
disable = false
port = 8179
interface = "127.0.0.1"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[ipc]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub"]

[mining]
author = "0xda1e1cf8bbc40ffedf7c1a3f0952be541cc62f97"
engine_signer = "0xda1e1cf8bbc40ffedf7c1a3f0952be541cc62f97"
notify_work = ["http://localhost:3003"]
gas_cap = "6283184"
tx_gas_limit = "6283184"
force_sealing = true
reseal_on_txs = "none"
