[parity]
chain = "demo.json"
base_path = "parity3"

[account]
unlock = ["0x84c14aacc5d82fc361996435d49e5f8f54426478"]
password = ["node.pwds"] #节点parity0密码

[network]
port = 30303
min_peers = 6
max_peers = 12
nat = "any"
id = 6652
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_peers="./reservedPeers.enode"
reserved_only=false

[rpc]
port = 8548
interface = "all"
cors=["chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[websockets]
disable = false
port = 8178
interface = "127.0.0.1"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
hosts = ["all"]

[ipc]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "shh_pubsub"]

[mining]
author = "0x84c14aacc5d82fc361996435d49e5f8f54426478"
engine_signer = "0x84c14aacc5d82fc361996435d49e5f8f54426478"
notify_work = ["http://localhost:3004"]
gas_cap = "6283184"
tx_gas_limit = "6283184"
force_sealing = true
reseal_on_txs = "all"
